[versions]
agp = "8.3.1"
appcompat = "1.6.1"
coreKtxVersion = "1.12.0"
espressoCore = "3.5.1"
jodaTime = "2.12.7"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.0"
coreKtx = "1.12.0"
media = "1.7.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v190 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
joda-time = { module = "joda-time:joda-time", version.ref = "jodaTime" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

